### ISSUE TITLE
Backwards Snowballing: AttributeError: 'WorkOk' object has no attribute 'place'

### ISSUE THREAD

**Issue by JaFeRo** [JoaoFelipe/snowballing#5]
Windows10
Python 3.7.1

Hey there I am trying to use this for a project, however it seems I can not get it to run :(.

After setting up and deleting the example files I tried inserting two sample files to try it out. I could insert them just fine. However when I got to the "Backwards Snowballing" part I get error messages after calling the "BackwardSnowballing" Function Error below.

this does not always happen, it depends on the titles I am inserting. However all they are all proper bibtex style and properly recognized by the Converter Widget.

This is basically a vanilla clone from this Repository and all I did was to do the first step of inserting two initial works.

`BackwardSnowballing("wiegand2014a", articles=article_list)`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-d1699cae72f5> in <module>
----> 1 BackwardSnowballing("wiegand2014a", articles=article_list)

C:\ProgramData\Anaconda3\lib\site-packages\snowballing\snowballing.py in __init__(self, citation_var, citation_file, articles, force_citation_file)
    573             articles=articles,
    574             backward=True,
--> 575             force_citation_file=force_citation_file
    576         )
    577 

C:\ProgramData\Anaconda3\lib\site-packages\snowballing\snowballing.py in __init__(self, citation_var, citation_file, articles, backward, force_citation_file)
    303         self.view = VBox(hboxes)
    304 
--> 305         self.set_articles(articles)
    306         self.erase_article_form()
    307 

C:\ProgramData\Anaconda3\lib\site-packages\snowballing\snowballing.py in set_articles(self, articles)
    345     def set_articles(self, articles):
    346         """Set list of articles and restart slider"""
--> 347         self.articles = list(self.valid_articles(articles))
    348         self.disable_show = True
    349         self.selector_widget.value = 0

C:\ProgramData\Anaconda3\lib\site-packages\snowballing\snowballing.py in valid_articles(self, articles, show)
    417                 set_pyref(info, check_existence=True)
    418                 set_place(info, check_existence=True)
--> 419                 nwork = find_work_by_info(info, set())
    420 
    421             if not self.work:

C:\ProgramData\Anaconda3\lib\site-packages\snowballing\operations.py in find_work_by_info(paper, pyrefs)
    764 
    765     for key, work in worklist:
--> 766         work, letter = compare_paper_to_work(letter, key, work, paper)
    767         if work:
    768             return work

C:\ProgramData\Anaconda3\lib\site-packages\snowballing\operations.py in compare_paper_to_work(letter, key, work, paper)
    685     if "place" in paper:
    686         place = getattr(config.MODULES['places'], paper["place"], None)
--> 687         if place is not None and place.name == work.place.name:
    688             required -= 0.1
    689 

AttributeError: 'WorkOk' object has no attribute 'place'`

**Comment by JoaoFelipe** [comment]
This error usually occurs when you insert a work without the "place=" attribute. Try to run the first cells of Validate.ipynb or the following code to check it:

```python
from snowballing.operations import reload, load_work_map_all_years
from snowballing.models import Place
reload()
for _, w in load_work_map_all_years():
    if hasattr(w, "place1") or not isinstance(w.place, Place):
        print(w)
```
