### ISSUE TITLE
Erro no start com profile bibtex

### ISSUE THREAD

**Issue by RicardoSouzaMoura** [JoaoFelipe/snowballing#6]
Primeiramente parabéns pelo projeto. 
Estou a procura de uma ferramenta com a qual eu possa realizar o snowballing para fazer uma revisão sistemática e estou verificando se me adapto a sua.
Tive um problema já no inicio:
Este comando abaixo não identifica o argumento --profile. Tentei com -p e deu o mesmo problema.
$ snowballing start literature --profile bibtex

usage: snowballing [-h] {start,search,ref} ...
snowballing: error: unrecognized arguments: -p

Meu ambiente:
MacOS: 10.13.6
python: 3.8.2

Sem o parametro criou a pasta literature, mas, vendo a documentação, me pareceu que o uso do bibtex facilitaria a vida rsrsrs

Um abraço

**Comment by JoaoFelipe** [comment]
Oi Ricardo, você deve ter instalado a versão do PyPi, que esqueci de atualizar. Vou tentar atualizar hoje mais tarde ou amanhã. Enquanto isso, você pode instalar a versão do github localmente com o comando `pip install -e snowballing`, após clonar/baixar o projeto do github.

**Comment by RicardoSouzaMoura** [comment]
Oi Joao,
eu instalei pelo pip seguindo o que está no readme do github. Usei do jeito
que tá lá... sem a opcao -e.

Abs

Ricardo Moura
--------------------------------------------------


Em sáb., 25 de abr. de 2020 às 16:50, João Felipe N. Pimentel <
notifications@github.com> escreveu:
